version: 2
updates:
  # Python package updates (Flask, Frozen-Flask, Gunicorn, etc.)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Python package updates in the `src/` directory
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Docker base image updates (Python, Alpine, Debian, etc.)
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # CI/CD GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/ci_cd/github_actions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Jenkins pipeline updates (for future expansion)
  - package-ecosystem: "docker"
    directory: "/ci_cd/jenkins"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
