services:
    web:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "8000:8000"
        environment:
            FLASK_ENV: production
            FLASK_APP: src.run:app
        command: gunicorn -w 4 -b 0.0.0.0:8000 src.run:app
