name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install security tools
        run: |
          pip install --upgrade pip
          pip install bandit safety

      - name: Bandit Security Scan
        run: |
          bandit -r src/app

      - name: Safety Vulnerability Check
        run: |
          safety check -r docker/requirements.txt
